language: node_js
node_js:
  - 13

services:
  - docker

env:
  - DOCKER_IMAGE=udagram-reverseproxy
  - DOCKER_IMAGE=udagram-frontend
  - DOCKER_IMAGE=udagram-api-feed
  - DOCKER_IMAGE=udagram-api-user

jobs:
  fast_finish: true

install:
  - cd project/${DOCKER_IMAGE}
  - npm install

script:
  - docker --version
  - docker build -t ${DOCKER_IMAGE} .
  - docker tag ${DOCKER_IMAGE} drosvick/${DOCKER_IMAGE}:v4

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push drosvick/${DOCKER_IMAGE}
