apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: drosvick/udagram-frontend:v4
        name: udagram-frontend
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: POSTGRES_DB
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AWS_REGION
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws"
          readOnly: true
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret

---
apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80